#!/bin/bash

GIT_ROOT="$(git rev-parse --show-toplevel)"
LINT_VERSION="v1.43.0"
LINT_BIN="$GIT_ROOT/.golangci-lint"
GOIF_VERSION="v1.0.4"
GOIF_BIN="$GIT_ROOT/.go-oif"

set -e

if [ ! -f "$LINT_BIN" ]; then
    echo "Downloading dependencies (golangci-lint)..."
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GIT_ROOT" "$LINT_VERSION"
    mv "$GIT_ROOT/golangci-lint" "$LINT_BIN"
fi

if [ ! -f "$GOIF_BIN" ]; then
    echo "Downloading dependencies (go-oif)..."
    curl -sSfL https://raw.githubusercontent.com/heyvito/go-oif/main/install.sh | sh -s -- -b "$GIT_ROOT" "$GOIF_VERSION"
    mv "$GIT_ROOT/go-oif" "$GOIF_BIN"
fi

"$GOIF_BIN" ./...
"$LINT_BIN" run
